# fly.toml file para deploy no Fly.io
app = "Gestor-de-loja" # Deixe em branco ou coloque o nome do seu app cadastrado no Fly.io

primary_region = "gru" # Configurado para São Paulo (Brasil) por padrão

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
